site_name: GitHub API Package

nav:
  - Home: 'index.md'
  - Getting Started: 'readme.md'
  - Test: 'test.md'
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences